-- EXERCISE SET (1) FOR FUNCTIONS
USE sakila;

-- 1. Find the total number of films available in the database.
SELECT COUNT(film_id) AS total_film
FROM film;

-- 2. Display the average rental rate of all films, rounded to 2 decimal places.
SELECT ROUND(AVG(rental_rate), 2) AS avg_rental_rate
FROM film;

-- 3. Show each rating and the average replacement cost for that rating.
SELECT rating, AVG(replacement_cost) AS avg_rep_cost
FROM film
GROUP BY rating;

-- 4. Find the longest film duration (in minutes) in the film table.
SELECT MAX(length) AS max_film_length
FROM film;

-- 5 Retrieve the number of customers per store.
SELECT store_id, COUNT(customer_id) AS customer_count
FROM customer
GROUP BY store_id;

-- 6. Display the month-wise total payment amount (ignore year).
SELECT MONTH(payment_date) AS pay_month, SUM(amount) AS total_payment
FROM payment
GROUP BY MONTH(payment_date);

-- 7. Show the first name in uppercase and last name in lowercase for all customers.
SELECT UPPER(first_name) AS first_name_upper,
       LOWER(last_name) AS last_name_lower
FROM customer;

-- 8. Find how many payments were made on each date in August 2005.
SELECT DATE(payment_date) AS pay_date, COUNT(payment_id) AS payment_count
FROM payment
WHERE MONTH(payment_date) = 08 AND YEAR(payment_date) = 2005
GROUP BY DATE(payment_date);

-- 9. Retrieve the shortest film length for each rating, but only show ratings where the shortest film is less than 60 minutes.
SELECT rating, MIN(length) AS shortest
FROM film
GROUP BY rating
HAVING MIN(length) < 60; 

-- 10. Show the total revenue generated by each staff member, rounded to 1 decimal place.
SELECT staff_id, ROUND(SUM(amount), 1) AS revenue
FROM payment
GROUP BY staff_id;